//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GM_LocationManagers
    {
        public int Id { get; set; }
        public int LocationId { get; set; }
        public int Role { get; set; }
        public string ManagerEIN { get; set; }
        public string ManagerName { get; set; }
        public string ManagerTitle { get; set; }
        public string ManagerPhone { get; set; }
        public string ManagerEmail { get; set; }
        public int ManagerDisplayOrder { get; set; }
    
        public virtual GM_Roles GM_Roles { get; set; }
        public virtual GM_Locations GM_Locations { get; set; }
    }
}
