//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsManager.Domain
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GoogleMapsData
    {
        public int id { get; set; }
        public string SitecoreId { get; set; }
        public string PlantId { get; set; }

        [Required]
        public string Title { get; set; }

        public string Subtitle { get; set; }
        public string Address { get; set; }
        public string Suite { get; set; }
        public string Locality { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Telephone { get; set; }

        [Required]
        public Nullable<decimal> Latitude { get; set; }

        [Required]
        public Nullable<decimal> Longitude { get; set; }

        [Required]
        public string Region { get; set; }

        public string ProductTypes { get; set; }
        public string FacilityTypes { get; set; }
        public string PlantManager { get; set; }
        public string PlantManagerEmail { get; set; }
        public string Operations { get; set; }
        public string OperationsEmail { get; set; }
        public string HR { get; set; }
        public string HREmail { get; set; }
        public string Sales { get; set; }
        public string SalesEmail { get; set; }
        [System.Web.Mvc.AllowHtml]
        public string PlantSummary { get; set; }
    }
}
