//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsManager.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntranetResourcesEntities : DbContext
    {
        public IntranetResourcesEntities()
            : base("name=IntranetResourcesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RKTN_CountryCodes> RKTN_CountryCodes { get; set; }
        public virtual DbSet<RKTN_People> RKTN_People { get; set; }
        public virtual DbSet<GM_FacilityTypes> GM_FacilityTypes { get; set; }
        public virtual DbSet<GM_LocationManagers> GM_LocationManagers { get; set; }
        public virtual DbSet<GM_Regions> GM_Regions { get; set; }
        public virtual DbSet<GM_Roles> GM_Roles { get; set; }
        public virtual DbSet<GM_Locations> GM_Locations { get; set; }
        public virtual DbSet<GM_Products> GM_Products { get; set; }
        public virtual DbSet<GoogleMapsData> GoogleMapsDatas { get; set; }
    }
}
