//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKTN_CountryCodes
    {
        public string ID { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public string PhoneCountryCode { get; set; }
        public string PostalCodeValidation { get; set; }
        public string SetID { get; set; }
    }
}
