//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapsManager.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class RKTN_People
    {
        public int ID { get; set; }
        public string EIN { get; set; }
        public string UserID { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string FirstName { get; set; }
        public string CommonName { get; set; }
        public string MidInit { get; set; }
        public string CostCenter { get; set; }
        public string Employer { get; set; }
        public string Level01 { get; set; }
        public string Level02 { get; set; }
        public string Department { get; set; }
        public string Worksite { get; set; }
        public string PositionCode { get; set; }
        public string Status { get; set; }
        public bool Salaried { get; set; }
        public bool IsUnion { get; set; }
        public Nullable<bool> IsTerminated { get; set; }
        public Nullable<int> FloorID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public string Extension { get; set; }
        public string Fax { get; set; }
        public string MobilePhone { get; set; }
        public string Pager { get; set; }
        public Nullable<System.DateTime> DateOfHire { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MaritalStatus { get; set; }
        public string Sex { get; set; }
        public string Race { get; set; }
        public string PrimaryLanguage { get; set; }
        public string EEOJobCode { get; set; }
        public string SpouseName { get; set; }
        public Nullable<System.DateTime> SpouseDOB { get; set; }
        public bool PublishHomePhone { get; set; }
        public bool PublishHomeAddress { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string PayrollSystem { get; set; }
        public Nullable<System.DateTime> LastPayDate { get; set; }
        public string SSN { get; set; }
        public string HasTimeCard { get; set; }
        public Nullable<decimal> HourlyBaseRate { get; set; }
        public string SupervisorEIN { get; set; }
        public string BadgeNumber { get; set; }
        public Nullable<System.DateTime> SeniorityDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string UnionCode { get; set; }
        public string ShiftCode { get; set; }
        public string LeaveCode { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public string SSOPwd { get; set; }
        public string newAddress1 { get; set; }
        public string newAddress2 { get; set; }
        public string TMEmailSent { get; set; }
        public string LegacyEIN { get; set; }
        public string PositionTitle { get; set; }
        public string EmployeeStatus { get; set; }
        public string JobCode { get; set; }
        public string RegTemp { get; set; }
        public string FullPart { get; set; }
        public string SupervisorPositionCode { get; set; }
        public string LegacyPositionCode { get; set; }
        public string LegacyWorksite { get; set; }
        public string LegacySupervisorEIN { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string Area { get; set; }
        public string Region { get; set; }
        public string PayGroup { get; set; }
        public string PSDivision { get; set; }
        public string PSBusinessUnit { get; set; }
        public string PSDeptID { get; set; }
        public string PSWorksite { get; set; }
        public string PSEmployer { get; set; }
        public string PSEmploymentType { get; set; }
        public string RecordSource { get; set; }
        public string AddedBy { get; set; }
        public string PER_ORG { get; set; }
        public string EMPL_CLASS { get; set; }
        public string ZPS_LEADER { get; set; }
        public string ZPS_SEGMENT { get; set; }
        public string ZPS_GROUP { get; set; }
        public string ZPS_FUNCTION { get; set; }
        public string APPROVER { get; set; }
        public string JOBCODE_DESCSHORT { get; set; }
        public string SEG_DESCR { get; set; }
        public string GRP_DESCR { get; set; }
        public string FUNC_DESCR { get; set; }
    }
}
